version: '3.8'

services:
  db:
    build: .
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: matching_orders
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql